services:
  localstack:
    image: localstack/localstack:3.8.1
    container_name: devops-localstack
    ports: ['4566:4566']
    environment:
      SERVICES: s3,ec2,iam,sts
      AWS_DEFAULT_REGION: ap-south-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
